"""Seting Unique

Revision ID: 790840baf837
Revises: f6feb7eea2e6
Create Date: 2025-11-13 13:11:43.867518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790840baf837'
down_revision: Union[str, Sequence[str], None] = 'f6feb7eea2e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activitiesproduct',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('activities_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activities_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activities_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activitiesproduct')
    # ### end Alembic commands ###
