"""Adding Models

Revision ID: 90f7ee9975a2
Revises: 
Create Date: 2025-11-16 16:40:12.077575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f7ee9975a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('building',
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=2, scale=5), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=2, scale=5), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activitiesproduct',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('activities_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activities_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.JSON(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organization_activities',
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('activitiesproduct_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activitiesproduct_id'], ['activitiesproduct.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_activities')
    op.drop_table('organization')
    op.drop_table('activitiesproduct')
    op.drop_table('building')
    op.drop_table('activities')
    # ### end Alembic commands ###
