"""Seting Unique

Revision ID: f6feb7eea2e6
Revises: a5ec1d686d1f
Create Date: 2025-11-13 12:22:15.893995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6feb7eea2e6'
down_revision: Union[str, Sequence[str], None] = 'a5ec1d686d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'activities', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='unique')
    # ### end Alembic commands ###
